# Generated by Django 3.2.25 on 2024-10-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
